language: node_js
node_js: stable

# S: Build Lifecycle
install:
  - npm install


#before_script:
 # - npm install -g gulp

script:
  - hexo g

after_script:
  - cd ./public
  - git init
  - git config user.name "pauljun"
  - git config user.email "467655062@qq.com"
  - git add .
  - git commit -m "Update docs"
  - git push --force --quiet "https://${token}@${GH_REF}" master:master
  - git push -u origin master
# E: Build LifeCycle

branches:
  only:
    - devplover
env:
 global:
   - GH_REF: github.com/pauljun/pauljun.github.io.git